apiVersion: kubeone.k8c.io/v1beta2
kind: KubeOneCluster
name: homelab

versions:
  # renovate: datasource=github-releases depName=kubernetes packageName=kubernetes/kubernetes
  kubernetes: '1.34.3' # check version here: https://kubernetes.io/releases/

cloudProvider:
  none: {}

clusterNetwork:
  cni:
    external: {}
  # ipFamily: IPv4

controlPlane:
  hosts:
    - publicAddress: '172.16.4.27'
      privateAddress: '172.16.4.27'
      sshUsername: steled
      sshPrivateKeyFile: '/home/steled/.ssh/steled.id_rsa'
      taints: []

staticWorkers:
  hosts:
    - publicAddress: '172.16.4.28'
      privateAddress: '172.16.4.28'
      sshUsername: steled
      sshPrivateKeyFile: '/home/steled/.ssh/steled.id_rsa'
      taints: []

# Provide the external address of your load balancer or the public addresses of
# the first control plane nodes.
apiEndpoint:
  host: '172.16.4.27'
  port: 6443

machineController:
  deploy: false

operatingSystemManager:
  deploy: false

addons:
  enable: true
  path: "./addons"
  addons:
    - name: backups-restic
      params:
        resticPassword: "m0VX36XVAbq1Rt6HJHXVSOJyjnaL"
        s3Bucket: "s3:s3.steled.org/kubeone-backup"
        awsDefaultRegion: "eu-east-local"
    - name: unattended-upgrades

helmReleases:
  - chart: cilium
    repoURL: https://helm.cilium.io/
    namespace: kube-system
    # renovate: datasource=github-releases depName=cilium packageName=cilium/cilium
    version: 1.19.0 # get version from here: https://helm.cilium.io/
    values:
      - valuesFile: ./values/01_defaults/cilium-values.yaml
  - chart: istio/base
    repoURL: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
    # renovate: datasource=github-releases depName=istio packageName=istio/istio
    version: 1.28.3 # check version here: https://istio.io/latest/news/releases/
    values:
      - valuesFile: ./values/01_defaults/istio-base-values.yaml
  - chart: istio/istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
    # renovate: datasource=github-releases depName=istio packageName=istio/istio
    version: 1.28.3 # check version here: https://istio.io/latest/news/releases/
    values:
      - valuesFile: ./values/01_defaults/istiod-values.yaml
  - chart: istio/cni
    repoURL: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
    # renovate: datasource=github-releases depName=istio packageName=istio/istio
    version: 1.28.3 # check version here: https://istio.io/latest/news/releases/
    values:
      - valuesFile: ./values/01_defaults/istio-cni-values.yaml
  - chart: istio/ztunnel
    repoURL: https://istio-release.storage.googleapis.com/charts
    namespace: istio-system
    # renovate: datasource=github-releases depName=istio packageName=istio/istio
    version: 1.28.3 # check version here: https://istio.io/latest/news/releases/
  - chart: istio/gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    namespace: istio-ingress
    # renovate: datasource=github-releases depName=istio packageName=istio/istio
    version: 1.28.3 # check version here: https://istio.io/latest/news/releases/
    values:
      - valuesFile: ./values/01_defaults/istio-gateway-values.yaml
  - chart: kured
    repoURL: https://kubereboot.github.io/charts
    namespace: kube-system
    # renovate: datasource=github-releases depName=kured packageName=kubereboot/charts
    version: 5.11.0 # check version here: https://github.com/kubereboot/charts/releases
    values:
      - valuesFile: ./values/01_defaults/kured-values.yaml
      # - valuesFile: ./values/02_secrets/kured-values.yaml
