apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    shared-gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    shared-gateway-access: "true"
